# Generated by Django 6.0 on 2025-12-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='detail',
        ),
    ]
