# Generated by Django 6.0 on 2025-12-25 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_goal_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='detail',
        ),
    ]
