# Generated by Django 6.0 on 2025-12-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_todo_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
